<?php

?>

<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/css/layout.css" type="text/css">
    <script src="/js/posts.js"></script>
    <title>Записи</title>
</head>
<body>
<h1 class="page-title">Записи</h1>
<main class="main">
    <section class="container">
      <div class="card">
          <form class="form" action="/" method="get">
              <input class="form__input" name="comment" type="text" placeholder="Введите слова" value="<?=$query ?? ''?>">
              <button class="form__submit">Поиск</button>
          </form>
      </div>
    </section>

    <section class="container posts" data-posts>
        <?php foreach ($comments as $comment): ?>
            <div class="card post">
                <h2 class="post__title"><?= $comment->post_title ?></h2>
                <p class="post__comment"><?= $comment->comment_body ?></p>
            </div>
        <?php endforeach; ?>
    </section>
</main>
</body>
</html>
